In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

from torchvision import datasets
import torchvision.transforms.functional as TF
from torchvision.transforms.functional  import InterpolationMode

import numpy as np
from matplotlib import pyplot as plt

In [2]:
## Batch Norm
## Dropout
## convolution
## MaxPool

In [2]:
torch.manual_seed(1)
t1 = torch.rand(4, 3, 5, 6)

In [6]:
t1.shape

torch.Size([4, 3, 5, 6])

In [7]:
bn = nn.BatchNorm2d(3)

In [13]:
d = t1[:, 0, :, :]
m = d.mean()
s = d.std(unbiased=False)

In [14]:
(d - m )/s

tensor([[[ 0.9627, -0.8485, -0.3799,  0.8758, -1.7952,  1.1225],
         [-0.4023,  0.9503,  0.2503, -0.2447,  0.5123,  0.0805],
         [ 0.6786, -0.7506, -0.1509, -0.1833,  0.2616, -0.0204],
         [ 1.6421,  0.5763, -0.7179, -1.1563, -0.3302, -0.8295],
         [-0.6195,  0.0778,  1.1157,  1.0162, -1.8636,  1.1608]],

        [[ 0.5958, -1.4325,  0.3675,  0.4419, -1.2805, -0.9111],
         [ 0.6327,  0.3263, -0.8182, -0.5860,  1.7211, -0.3631],
         [ 1.0545,  0.8069, -1.2366, -1.6229,  1.8044,  0.0860],
         [ 1.2849,  0.3795,  0.5960,  1.4013,  1.7823, -1.2691],
         [ 0.2239,  1.4000,  1.3587,  1.1633, -1.3830, -1.3762]],

        [[-0.4863, -0.1659, -1.6438, -0.3868, -1.2339,  1.7268],
         [-1.6496, -1.4886, -0.0771, -1.0365,  0.6646, -0.7416],
         [-0.9021,  0.0944,  1.3576, -1.3446,  0.8762,  1.2034],
         [ 1.8391, -1.3380,  0.4457, -1.4127,  1.6035, -0.7472],
         [ 1.1275,  0.0435, -0.1603, -0.0733,  0.3090,  0.8796]],

        [[ 0.5226, 

In [17]:
class BN(nn.Module):

    def __init__(self, bn):
        super().__init__()
        self.batchnorm = nn.BatchNorm2d(bn)

    def forward(self, x):
        return self.batchnorm(x)

In [20]:
class BN:

    def __init__(self, bn):
        self.batchnorm = nn.BatchNorm2d(bn)

    def __call__(self, x):
        return self.batchnorm(x)

In [21]:
bn = BN(3)

In [22]:
bn(t1)

tensor([[[[ 0.9626, -0.8484, -0.3798,  0.8757, -1.7951,  1.1225],
          [-0.4023,  0.9502,  0.2503, -0.2446,  0.5122,  0.0805],
          [ 0.6786, -0.7506, -0.1509, -0.1833,  0.2615, -0.0204],
          [ 1.6420,  0.5763, -0.7178, -1.1562, -0.3302, -0.8294],
          [-0.6195,  0.0778,  1.1157,  1.0161, -1.8634,  1.1607]],

         [[ 0.3966,  1.5071,  1.0283, -1.5789, -1.6447, -0.8673],
          [ 1.3902, -0.3434,  0.6432, -0.8381,  1.5613, -0.7690],
          [ 1.1775, -0.0473, -0.9411,  0.7860, -0.9478,  0.4211],
          [-0.5461, -0.2489, -1.6623, -0.8581,  0.8335, -0.4703],
          [ 1.5859,  1.2632, -0.1447, -1.1746,  0.9435,  0.4480]],

         [[-1.1304,  1.1259,  1.0520,  1.5391, -0.9809, -0.2915],
          [-0.0387,  0.2493, -1.3262, -1.2404,  0.9421, -0.4132],
          [ 0.8455,  0.0943,  0.5667,  0.3779,  0.6280,  0.8581],
          [-1.6173,  0.8714, -1.2291, -1.3186,  0.1009, -0.3016],
          [ 1.0176, -1.0132, -1.5527,  1.2621, -0.2631,  0.9743]]],


  

In [23]:
## convolution

In [54]:
conv = nn.Conv2d(in_channels=3, out_channels=3, kernel_size=3)

In [55]:
w, b= conv.weight, conv.bias

In [59]:
(t1[0,:,0:3, 0:3] * w[0, :, :, :]).sum() + b[0]

tensor(0.3910, grad_fn=<AddBackward0>)

In [61]:
patch = t1[0,:,0:3, 0:3]
kernel = w[0, : , :, :]

In [72]:
patch.flatten() @ kernel.flatten() + b[0]

tensor(0.3910, grad_fn=<AddBackward0>)

In [74]:
patch.flatten(),  kernel.flatten()

(tensor([0.7576, 0.2793, 0.4031, 0.3971, 0.7544, 0.5695, 0.6826, 0.3051, 0.4635,
         0.6397, 0.9743, 0.8300, 0.9391, 0.4167, 0.7140, 0.8750, 0.5059, 0.2366,
         0.1768, 0.8248, 0.8036, 0.4903, 0.5730, 0.1205, 0.7442, 0.5285, 0.6642]),
 tensor([-0.0523,  0.0535,  0.0424,  0.1300,  0.0705,  0.0876,  0.1698,  0.0599,
          0.0286, -0.0701,  0.1411,  0.0284,  0.1240,  0.1858, -0.0430,  0.1355,
         -0.0391,  0.1737,  0.1515, -0.0690,  0.0069, -0.0840, -0.0778, -0.0390,
         -0.0013, -0.0671, -0.1817], grad_fn=<ViewBackward0>))

In [78]:
torch.einsum("k a, k b -> ",patch.flatten().reshape(-1,1) , kernel.flatten().reshape(-1,1) ) + b[0]

tensor(0.3910, grad_fn=<AddBackward0>)

In [58]:
conv(t1)

tensor([[[[ 0.3910,  0.5273,  0.1807,  0.4996],
          [ 0.4197,  0.3916,  0.2708,  0.2294],
          [ 0.5709,  0.2583,  0.4447,  0.2861]],

         [[-0.4533, -0.3284, -0.1917, -0.1318],
          [-0.2882, -0.3397, -0.4648, -0.2975],
          [-0.2117, -0.4026, -0.2993, -0.3454]],

         [[-0.5270, -0.7281, -0.5801, -0.5886],
          [-0.9294, -0.3778, -0.8430, -0.8400],
          [-0.4422, -0.6454, -0.7699, -0.8810]]],


        [[[ 0.4651,  0.6441,  0.4633,  0.5102],
          [ 0.5073,  0.3547,  0.5353,  0.5163],
          [ 0.4098,  0.4945,  0.6449,  0.4748]],

         [[-0.6090, -0.4577, -0.4907, -0.4408],
          [-0.1128, -0.5560, -0.2180, -0.5869],
          [-0.3400, -0.3121, -0.4739, -0.4369]],

         [[-0.9008, -0.7996, -0.6355, -0.2133],
          [-0.6253, -0.8986, -0.7546, -0.5307],
          [-0.7940, -0.7096, -0.9564, -0.9706]]],


        [[[ 0.2441,  0.0754,  0.5989,  0.2227],
          [ 0.1132,  0.2037,  0.4981,  0.0569],
          [ 0.4945,  0.5

In [79]:
mp = nn.MaxPool2d(3)

In [90]:
ap1 = nn.AvgPool2d(kernel_size=3)

In [99]:
ap = nn.AdaptiveAvgPool2d(output_size=2)

In [87]:
sum([0.7576, 0.2793 , 0.3971, 0.7544])/4

0.5471

In [92]:
sum([0.7576, 0.2793, 0.4031] + [0.3971, 0.7544, 0.5695] + [0.6826, 0.3051, 0.4635])/9

0.5124666666666666

In [85]:
t1

tensor([[[[0.7576, 0.2793, 0.4031, 0.7347, 0.0293, 0.7999],
          [0.3971, 0.7544, 0.5695, 0.4388, 0.6387, 0.5247],
          [0.6826, 0.3051, 0.4635, 0.4550, 0.5725, 0.4980],
          [0.9371, 0.6556, 0.3138, 0.1980, 0.4162, 0.2843],
          [0.3398, 0.5239, 0.7981, 0.7718, 0.0112, 0.8100]],

         [[0.6397, 0.9743, 0.8300, 0.0444, 0.0246, 0.2588],
          [0.9391, 0.4167, 0.7140, 0.2676, 0.9906, 0.2885],
          [0.8750, 0.5059, 0.2366, 0.7570, 0.2346, 0.6471],
          [0.3556, 0.4452, 0.0193, 0.2616, 0.7713, 0.3785],
          [0.9980, 0.9008, 0.4766, 0.1663, 0.8045, 0.6552]],

         [[0.1768, 0.8248, 0.8036, 0.9434, 0.2197, 0.4177],
          [0.4903, 0.5730, 0.1205, 0.1452, 0.7720, 0.3828],
          [0.7442, 0.5285, 0.6642, 0.6099, 0.6818, 0.7479],
          [0.0369, 0.7517, 0.1484, 0.1227, 0.5304, 0.4148],
          [0.7937, 0.2104, 0.0555, 0.8639, 0.4259, 0.7812]]],


        [[[0.6607, 0.1251, 0.6004, 0.6201, 0.1652, 0.2628],
          [0.6705, 0.5896, 0.287

In [100]:
ap(t1)

tensor([[[[0.5125, 0.5213],
          [0.5577, 0.4463]],

         [[0.6812, 0.3904],
          [0.5348, 0.5196]],

         [[0.5473, 0.5467],
          [0.4371, 0.5754]]],


        [[[0.5121, 0.4826],
          [0.6756, 0.5206]],

         [[0.6161, 0.5819],
          [0.5352, 0.6581]],

         [[0.5373, 0.3509],
          [0.5859, 0.5337]]],


        [[[0.3578, 0.4954],
          [0.5770, 0.5414]],

         [[0.4006, 0.6797],
          [0.4814, 0.5147]],

         [[0.3783, 0.5857],
          [0.5816, 0.5839]]],


        [[[0.5157, 0.4799],
          [0.4969, 0.4361]],

         [[0.4607, 0.4436],
          [0.4777, 0.3854]],

         [[0.5471, 0.3234],
          [0.5785, 0.4491]]]])

In [95]:
ap1(t1)

tensor([[[[0.5125, 0.5213]],

         [[0.6812, 0.3904]],

         [[0.5473, 0.5467]]],


        [[[0.5121, 0.4826]],

         [[0.6161, 0.5819]],

         [[0.5373, 0.3509]]],


        [[[0.3578, 0.4954]],

         [[0.4006, 0.6797]],

         [[0.3783, 0.5857]]],


        [[[0.5157, 0.4799]],

         [[0.4607, 0.4436]],

         [[0.5471, 0.3234]]]])

In [6]:
dropout = nn.Dropout2d(p=0.50)

In [15]:
t1

tensor([[[[0.7576, 0.2793, 0.4031, 0.7347, 0.0293, 0.7999],
          [0.3971, 0.7544, 0.5695, 0.4388, 0.6387, 0.5247],
          [0.6826, 0.3051, 0.4635, 0.4550, 0.5725, 0.4980],
          [0.9371, 0.6556, 0.3138, 0.1980, 0.4162, 0.2843],
          [0.3398, 0.5239, 0.7981, 0.7718, 0.0112, 0.8100]],

         [[0.6397, 0.9743, 0.8300, 0.0444, 0.0246, 0.2588],
          [0.9391, 0.4167, 0.7140, 0.2676, 0.9906, 0.2885],
          [0.8750, 0.5059, 0.2366, 0.7570, 0.2346, 0.6471],
          [0.3556, 0.4452, 0.0193, 0.2616, 0.7713, 0.3785],
          [0.9980, 0.9008, 0.4766, 0.1663, 0.8045, 0.6552]],

         [[0.1768, 0.8248, 0.8036, 0.9434, 0.2197, 0.4177],
          [0.4903, 0.5730, 0.1205, 0.1452, 0.7720, 0.3828],
          [0.7442, 0.5285, 0.6642, 0.6099, 0.6818, 0.7479],
          [0.0369, 0.7517, 0.1484, 0.1227, 0.5304, 0.4148],
          [0.7937, 0.2104, 0.0555, 0.8639, 0.4259, 0.7812]]],


        [[[0.6607, 0.1251, 0.6004, 0.6201, 0.1652, 0.2628],
          [0.6705, 0.5896, 0.287

In [14]:
t1[2], td[2]

(tensor([[[0.3750, 0.4596, 0.0693, 0.4012, 0.1775, 0.9595],
          [0.0677, 0.1103, 0.4830, 0.2296, 0.6789, 0.3075],
          [0.2652, 0.5283, 0.8619, 0.1483, 0.7348, 0.8212],
          [0.9891, 0.1500, 0.6211, 0.1303, 0.9269, 0.3060],
          [0.8012, 0.5149, 0.4611, 0.4840, 0.5850, 0.7357]],
 
         [[0.5802, 0.6525, 0.0502, 0.8643, 0.9359, 0.9133],
          [0.8696, 0.1392, 0.3146, 0.9409, 0.1192, 0.9536],
          [0.1068, 0.1478, 0.7444, 0.1408, 0.3854, 0.8637],
          [0.8960, 0.9729, 0.3985, 0.1114, 0.9923, 0.3935],
          [0.2943, 0.6219, 0.1503, 0.8286, 0.8134, 0.1033]],
 
         [[0.0893, 0.4562, 0.7100, 0.4855, 0.2465, 0.5114],
          [0.0300, 0.1466, 0.1672, 0.9118, 0.9408, 0.3302],
          [0.5224, 0.7230, 0.5599, 0.2496, 0.7884, 0.8074],
          [0.4710, 0.4384, 0.9544, 0.9371, 0.2165, 0.9892],
          [0.6237, 0.1679, 0.7737, 0.1267, 0.9620, 0.1786]]]),
 tensor([[[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.00

In [11]:
td = dropout(t1)

In [15]:
class F:

    def __init__(self, n):
        self.n = n
        self.a = 0
        self.b = 1
        
    def __call__(self):
        for i in range(self.n):
            temp = self.b
            self.b =  self.b + self.a
            self.a = temp
            yield self.b



In [16]:
f = F(10)

In [17]:
list(f())

[1, 2, 3, 5, 8, 13, 21, 34, 55, 89]