In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

import numpy as np
from matplotlib import pyplot as plt

In [ ]:
## __call__
## forward

class Fibonacci:

    def __init__(self, n):
        self.n = n
        self.a = 0
        self.b = 1
    
    ## compute/ any name 
    ## we can replace with .compute() instead __call__() , the .compute can be of any name (i choose this one)
    ## but then you have to call this via .compute() instead f()
    def __call__(self):
        for i in range(self.n):
            temp = self.b # temp = 1, 1
            self.b = self.a + self.b #  b= 0 + 1, 1 + 1 = 2
            self.a = temp # a=1, 1
            yield self.b


    

In [15]:
f = Fibonacci(10)

In [10]:
type(f)

__main__.Fibonacci

In [ ]:
# f.compute() # will work only if the class has a method called compute
# f() # if there __call__ then use f()
# Should we use call in pytorch always - Not necessary infact use nn.Module and subclass it because you get free hooks and other objects
# which __call__ may not have (this is something when in training large network one can observer)
# __call__ can be very useful when we want to create a new thing from scratch and hence it's good to know thing but may not be useful for already created abstraction


<generator object Fibonacci.compute at 0x000001634D0E3440>

In [16]:
# list(f.compute())
# list(f())

In [17]:
torch.manual_seed(1)
t = torch.rand(4, 3, 5, 6)

In [18]:
t.shape

torch.Size([4, 3, 5, 6])

In [21]:
##  (x- mu) / sigma
t.size(1)

3

In [ ]:
bn = nn.BatchNorm2d(3)
## running_mean
## running_std_dev
## beta
## gamma


In [ ]:
## nn.Module
## __call__

## Inheritance -> extend the class but still an animal 'is a' relationship
## Composition -> extend the class but modfies it as well 'has a' horse with wings may not be an animal but a pegasus !!!
## Mixins ## BaseEstimator -> sklearn -> TransformerMixins -> mixins are extended actions where parent class tell you to implement something which is mandatory .forward() in this case or 
## in sklearn we have .set and .get related attributes .get_features_names_out() etc.
## Mixins also helps to bind various differnt objects in the context of sklearn or in pytorch
## We can use multiple mixins in a same class by comma separation

class Animal:
    pass
class Horse(Animal):
    pass

In [ ]:
class BN(nn.Module):
    ## abstarct base class
    def __init__(self, n=None):
        super().__init__()
        self.batchnorm = nn.BatchNorm2d(n)
    
    ## __call__
    def forward(self, x):
        return self.batchnorm(x)

In [35]:
class BN2:
    ## abstarct base class
    def __init__(self, n=None):
        self.batchnorm = nn.BatchNorm2d(n)
    
    ## __call__
    def __call__(self, x):
        return self.batchnorm(x)

In [36]:
bn2 = BN2(3)
bn2(t)

tensor([[[[ 0.9626, -0.8484, -0.3798,  0.8757, -1.7951,  1.1225],
          [-0.4023,  0.9502,  0.2503, -0.2446,  0.5122,  0.0805],
          [ 0.6786, -0.7506, -0.1509, -0.1833,  0.2615, -0.0204],
          [ 1.6420,  0.5763, -0.7178, -1.1562, -0.3302, -0.8294],
          [-0.6195,  0.0778,  1.1157,  1.0161, -1.8634,  1.1607]],

         [[ 0.3966,  1.5071,  1.0283, -1.5789, -1.6447, -0.8673],
          [ 1.3902, -0.3434,  0.6432, -0.8381,  1.5613, -0.7690],
          [ 1.1775, -0.0473, -0.9411,  0.7860, -0.9478,  0.4211],
          [-0.5461, -0.2489, -1.6623, -0.8581,  0.8335, -0.4703],
          [ 1.5859,  1.2632, -0.1447, -1.1746,  0.9435,  0.4480]],

         [[-1.1304,  1.1259,  1.0520,  1.5391, -0.9809, -0.2915],
          [-0.0387,  0.2493, -1.3262, -1.2404,  0.9421, -0.4132],
          [ 0.8455,  0.0943,  0.5667,  0.3779,  0.6280,  0.8581],
          [-1.6173,  0.8714, -1.2291, -1.3186,  0.1009, -0.3016],
          [ 1.0176, -1.0132, -1.5527,  1.2621, -0.2631,  0.9743]]],


  

In [32]:
bn = BN(3)

In [38]:
bn(t)

tensor([[[[ 0.9626, -0.8484, -0.3798,  0.8757, -1.7951,  1.1225],
          [-0.4023,  0.9502,  0.2503, -0.2446,  0.5122,  0.0805],
          [ 0.6786, -0.7506, -0.1509, -0.1833,  0.2615, -0.0204],
          [ 1.6420,  0.5763, -0.7178, -1.1562, -0.3302, -0.8294],
          [-0.6195,  0.0778,  1.1157,  1.0161, -1.8634,  1.1607]],

         [[ 0.3966,  1.5071,  1.0283, -1.5789, -1.6447, -0.8673],
          [ 1.3902, -0.3434,  0.6432, -0.8381,  1.5613, -0.7690],
          [ 1.1775, -0.0473, -0.9411,  0.7860, -0.9478,  0.4211],
          [-0.5461, -0.2489, -1.6623, -0.8581,  0.8335, -0.4703],
          [ 1.5859,  1.2632, -0.1447, -1.1746,  0.9435,  0.4480]],

         [[-1.1304,  1.1259,  1.0520,  1.5391, -0.9809, -0.2915],
          [-0.0387,  0.2493, -1.3262, -1.2404,  0.9421, -0.4132],
          [ 0.8455,  0.0943,  0.5667,  0.3779,  0.6280,  0.8581],
          [-1.6173,  0.8714, -1.2291, -1.3186,  0.1009, -0.3016],
          [ 1.0176, -1.0132, -1.5527,  1.2621, -0.2631,  0.9743]]],


  

In [23]:
t

tensor([[[[0.7576, 0.2793, 0.4031, 0.7347, 0.0293, 0.7999],
          [0.3971, 0.7544, 0.5695, 0.4388, 0.6387, 0.5247],
          [0.6826, 0.3051, 0.4635, 0.4550, 0.5725, 0.4980],
          [0.9371, 0.6556, 0.3138, 0.1980, 0.4162, 0.2843],
          [0.3398, 0.5239, 0.7981, 0.7718, 0.0112, 0.8100]],

         [[0.6397, 0.9743, 0.8300, 0.0444, 0.0246, 0.2588],
          [0.9391, 0.4167, 0.7140, 0.2676, 0.9906, 0.2885],
          [0.8750, 0.5059, 0.2366, 0.7570, 0.2346, 0.6471],
          [0.3556, 0.4452, 0.0193, 0.2616, 0.7713, 0.3785],
          [0.9980, 0.9008, 0.4766, 0.1663, 0.8045, 0.6552]],

         [[0.1768, 0.8248, 0.8036, 0.9434, 0.2197, 0.4177],
          [0.4903, 0.5730, 0.1205, 0.1452, 0.7720, 0.3828],
          [0.7442, 0.5285, 0.6642, 0.6099, 0.6818, 0.7479],
          [0.0369, 0.7517, 0.1484, 0.1227, 0.5304, 0.4148],
          [0.7937, 0.2104, 0.0555, 0.8639, 0.4259, 0.7812]]],


        [[[0.6607, 0.1251, 0.6004, 0.6201, 0.1652, 0.2628],
          [0.6705, 0.5896, 0.287

In [26]:
m = t[:, 0, :, :].mean()
s = t[:, 0, :, :].std(unbiased=False)

In [27]:
(t[:, 0, :, :] - m )/s

tensor([[[ 0.9627, -0.8485, -0.3799,  0.8758, -1.7952,  1.1225],
         [-0.4023,  0.9503,  0.2503, -0.2447,  0.5123,  0.0805],
         [ 0.6786, -0.7506, -0.1509, -0.1833,  0.2616, -0.0204],
         [ 1.6421,  0.5763, -0.7179, -1.1563, -0.3302, -0.8295],
         [-0.6195,  0.0778,  1.1157,  1.0162, -1.8636,  1.1608]],

        [[ 0.5958, -1.4325,  0.3675,  0.4419, -1.2805, -0.9111],
         [ 0.6327,  0.3263, -0.8182, -0.5860,  1.7211, -0.3631],
         [ 1.0545,  0.8069, -1.2366, -1.6229,  1.8044,  0.0860],
         [ 1.2849,  0.3795,  0.5960,  1.4013,  1.7823, -1.2691],
         [ 0.2239,  1.4000,  1.3587,  1.1633, -1.3830, -1.3762]],

        [[-0.4863, -0.1659, -1.6438, -0.3868, -1.2339,  1.7268],
         [-1.6496, -1.4886, -0.0771, -1.0365,  0.6646, -0.7416],
         [-0.9021,  0.0944,  1.3576, -1.3446,  0.8762,  1.2034],
         [ 1.8391, -1.3380,  0.4457, -1.4127,  1.6035, -0.7472],
         [ 1.1275,  0.0435, -0.1603, -0.0733,  0.3090,  0.8796]],

        [[ 0.5226, 

In [22]:
bn(t)

tensor([[[[ 0.9626, -0.8484, -0.3798,  0.8757, -1.7951,  1.1225],
          [-0.4023,  0.9502,  0.2503, -0.2446,  0.5122,  0.0805],
          [ 0.6786, -0.7506, -0.1509, -0.1833,  0.2615, -0.0204],
          [ 1.6420,  0.5763, -0.7178, -1.1562, -0.3302, -0.8294],
          [-0.6195,  0.0778,  1.1157,  1.0161, -1.8634,  1.1607]],

         [[ 0.3966,  1.5071,  1.0283, -1.5789, -1.6447, -0.8673],
          [ 1.3902, -0.3434,  0.6432, -0.8381,  1.5613, -0.7690],
          [ 1.1775, -0.0473, -0.9411,  0.7860, -0.9478,  0.4211],
          [-0.5461, -0.2489, -1.6623, -0.8581,  0.8335, -0.4703],
          [ 1.5859,  1.2632, -0.1447, -1.1746,  0.9435,  0.4480]],

         [[-1.1304,  1.1259,  1.0520,  1.5391, -0.9809, -0.2915],
          [-0.0387,  0.2493, -1.3262, -1.2404,  0.9421, -0.4132],
          [ 0.8455,  0.0943,  0.5667,  0.3779,  0.6280,  0.8581],
          [-1.6173,  0.8714, -1.2291, -1.3186,  0.1009, -0.3016],
          [ 1.0176, -1.0132, -1.5527,  1.2621, -0.2631,  0.9743]]],


  

In [46]:
t.shape

torch.Size([4, 3, 5, 6])

In [ ]:
class Conv(nn.Module):

    def __init__(self, in_ch, out_ch, ker_size):
        super().__init__()
        self.conv = nn.Conv2d(in_ch, out_ch, ker_size)

    def forward(self, x):
        return self.conv(x)
    
## convolution
## BatchNorm

## Dropout
## AvgPool/MaxPool

In [77]:
## std deviation
## multiplication / sum 

x = torch.tensor([1, 2, 3, 4, 5, 6, 7], dtype=torch.float32)

In [80]:
x.mean(), x.std(unbiased=False)

(tensor(4.), tensor(2.))

In [82]:
y = x.clone().detach() + 10
y.mean(), y.std(unbiased=False)

(tensor(14.), tensor(2.))

In [ ]:
## BatchNorm always work against each of the channel (it's channel centric)
## Dropout is mostly dropping out channels not individual elements, dropping individual elements is useless and nearby pixel correlation are same
## However, the Dropout individual elements can be useful at very last layer in some cases

## Average pool or maxpool are positional invariant , which means a blonde woman sitting in center or side doesn't matter
## this is biggest take on average pool, pooling are very useful in that sense

## CNN opertaion view -> Convolution -> BatchNorm -> Relu -> Dropout -> MaxPool or averagePool
## Convolution (understanding a kernel basis on target)
## BatchNorm -> good for optimization of overall training, very good for faster convergence and a soft regularisation
## Relu -> remove useless outputs and adds non linearity -> variations include more softer versions like - parametric relu (softer and regularised)
## Dropout -> Hard regularisation (not very useful in modern context but still used)
## MaxPool -> Add invariancy 

## Regularisation can be perfomred in many ways -> algorithmic (lasso , ridge), data wise(bootstrapping), network /process (dropout/normalisation)
## What affetcs parameters in convolution process: kernel size, batchnorm (beta and gamma)
## AvgPool or maxpool affects indirectly especially if it's followed by GAP or Adatptive Avg Pool but if its followed by another CNN it doesn't truely affect as kernel size comes to play
## Relu and Dropout don't affect parameters


In [59]:
c = Conv(3, 3, 3)
c(t)

tensor([[[[ 0.0633, -0.1317, -0.1677, -0.2352],
          [-0.0906, -0.0896,  0.0924, -0.1099],
          [-0.0350,  0.0749, -0.4394, -0.0250]],

         [[-0.4023, -0.3884, -0.2634, -0.4226],
          [-0.2299, -0.2605, -0.3910, -0.2543],
          [-0.4839, -0.3565, -0.2023, -0.4193]],

         [[ 0.5371,  0.8799,  0.4230,  0.4781],
          [ 0.5541,  0.3858,  0.5193,  0.3163],
          [ 0.4560,  0.3543,  0.7628,  0.6780]]],


        [[[-0.0969, -0.3508,  0.1405, -0.1742],
          [-0.0160,  0.0525, -0.3493, -0.1805],
          [-0.0625, -0.1844,  0.1159, -0.0880]],

         [[-0.3959, -0.3762, -0.2963, -0.3984],
          [-0.4894, -0.4527, -0.3912, -0.2897],
          [-0.3915, -0.5286, -0.5863, -0.3869]],

         [[ 0.5216,  0.7319,  0.7237,  0.2839],
          [ 0.4428,  0.4773,  0.8299,  0.9606],
          [ 0.7206,  0.7935,  0.6807,  0.4602]]],


        [[[-0.0240, -0.1278, -0.0747,  0.0419],
          [-0.0421, -0.2178,  0.2176, -0.0894],
          [-0.0056, -0.1

In [ ]:
conv = nn.Conv2d(3, 3, 3)

In [47]:
#t
# 0.7576, 0.2793, 0.4031
# 0.3971, 0.7544, 0.5695
# 0.6826, 0.3051, 0.4635

In [56]:
t[0, :, 0:3, 0:3].flatten() @ conv.weight[0, :,:,:].flatten() + conv.bias[0]

tensor(-0.0264, grad_fn=<AddBackward0>)

In [70]:
(t[0, :, 0:3, 0:3].flatten() * conv.weight[0, :,:,:].flatten()).sum() + conv.bias[0]

tensor(-0.0264, grad_fn=<AddBackward0>)

In [74]:
torch.einsum("x k, x k ->", t[0, :, 0:3, 0:3].flatten().reshape(-1,1), conv.weight[0, :,:,:].flatten().reshape(-1,1) ) + conv.bias[0]

tensor(-0.0264, grad_fn=<AddBackward0>)

In [55]:
(t[0, :, 0:3, 0:3] * conv.weight[0, :,:,:]).sum() + conv.bias[0]

tensor(-0.0264, grad_fn=<AddBackward0>)

In [41]:
## sobel filter
conv.weight, conv.bias

(Parameter containing:
 tensor([[[[-0.1125, -0.1885,  0.1172],
           [-0.0280,  0.0791,  0.0095],
           [-0.1796, -0.0944,  0.0541]],
 
          [[-0.0390, -0.1858,  0.0675],
           [ 0.0074, -0.0618,  0.0777],
           [ 0.0406, -0.0710,  0.1729]],
 
          [[ 0.0965,  0.0242, -0.0370],
           [-0.1630,  0.1486, -0.0497],
           [-0.1244,  0.1234,  0.0683]]],
 
 
         [[[ 0.0476, -0.0382, -0.0601],
           [ 0.0327,  0.1489,  0.0276],
           [-0.0910,  0.1912,  0.0041]],
 
          [[ 0.1521,  0.0469,  0.1725],
           [ 0.1110, -0.0981,  0.1352],
           [ 0.0012, -0.1545, -0.0403]],
 
          [[-0.1737, -0.0997, -0.1363],
           [ 0.1316, -0.0404, -0.0333],
           [ 0.0922,  0.0783, -0.1270]]],
 
 
         [[[ 0.0709,  0.0818, -0.1530],
           [ 0.1673, -0.1171, -0.0753],
           [-0.1585,  0.1759,  0.0366]],
 
          [[ 0.1620,  0.0126,  0.1046],
           [-0.0614, -0.1535,  0.0309],
           [-0.0172, -0.0194, 

In [ ]:
conv(t)
## -.026408

tensor([[[[-2.6408e-02,  8.2194e-02,  5.2315e-02,  4.3743e-01],
          [-1.4597e-01, -1.1286e-01,  1.3487e-01,  3.7555e-03],
          [ 7.9016e-02,  1.6135e-02,  1.1587e-01,  1.1989e-01]],

         [[ 1.5112e-01, -1.7343e-01, -1.1458e-01, -2.9965e-01],
          [ 1.2368e-01,  1.1308e-01, -4.7922e-02, -2.2681e-02],
          [-1.6825e-01, -5.4032e-02, -2.1109e-01, -3.9716e-01]],

         [[ 2.3086e-01,  1.9498e-01,  4.0899e-01,  7.0503e-03],
          [ 3.0012e-01,  2.0463e-01,  7.6910e-02,  1.8476e-01],
          [ 5.1157e-01,  2.3109e-01,  2.1109e-01,  1.6062e-01]]],


        [[[ 1.4238e-01,  7.7480e-02,  1.3987e-01,  6.1119e-02],
          [-1.6402e-02, -7.2641e-02,  1.0013e-01, -8.5735e-02],
          [ 1.2615e-02, -4.6554e-02,  9.2191e-02, -1.8989e-02]],

         [[-8.7405e-03, -3.7294e-01,  3.8433e-02,  2.2596e-01],
          [ 9.9788e-02,  1.2479e-01, -4.3016e-02,  2.6204e-01],
          [ 1.6886e-01,  1.2488e-01,  1.4612e-01, -7.5648e-02]],

         [[ 3.6372e-01,  8.3

In [ ]:
## A dot product can be seen as sum-product and hence in 2d convolution we multiply and add 
## we can use alternate way as well like flatten and dot product
## we can use einsums as well though in simpler cases it's overkill but in complex cases it's very useful
## 

## 
# Homework: Implement class on MaxPool/AvgPool and Dropuot (like we did on convolution and batchnorm)
# Next class:
## Losses (regression and classification)
## Pytorch Many variations of same losses why there are many (which one to use and when to use)
## A common misconception is that losses are not present in unsupervised learning (not true) , even PCA and Kmeans has a loss but people don't discuss it much
## Losses are everywhere !!! (they are building blocks towards better learning !!!)